### PR TITLE
migrated SEIR function from other rep

### PR DESCRIPTION
**Pull request by emilIftekhar**

### CODE REVIEW

**Comment by jdehning** [comment]
@emilIftekhar it is saying that it has conflicts. Try to solve them, there are some tutorials for it, for example https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request

**Comment by jdehning** [comment]
There are still problems, that the file model.py gets completely rewritten, with an old version of it. See files changed, at the top bar.

**Comment by emilIftekhar** [comment]
Ok, I am sorry. I will check again where the differences are...


 

    Am Dienstag, 21. April 2020, 12:45:31 MESZ hat jdehning <notifications@github.com> Folgendes geschrieben:  
 
 


There are still problems, that the file model.py gets completely rewritten, with an old version of it. See files changed, at the top bar.

**Comment by jdehning** [comment]
> There are still problems, that the file model.py gets completely rewritten, with an old version of it. See files changed, at the top bar.

Sorry, my bad. When one ticks hide whitespace changes in the difference view, it does not show the whole file as new.

**Pull request merged**
